### ISSUE TITLE
Formal package required for installation

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#1]
Hi, interesting project and I like the cross platform support. I suggest don't install system from git, use a packaging mechanism to install exactly one version. On Linux I suggest /usr/share/kasini3000 would be a better location than /etc/kasini3000, the /etc location should only be for local configuration files. Use a DEB or RPM to install the required files on Linux. Likewise on Windows it would be better installed by MSI in c:\Program Files\kasini3000 with only local data files under c:\ProgramData\kasini3000. Using packages you can then update in place with new versions and use standard packaging mechanisms to know what is installed on any node. Data managed on Linux should be in say, /var/lib/kasini3000 rather that /etc/kasini3000.

**Comment by kasini3000** [comment]
### About installation:

*Msi packages and rpm packages are rarely available. Because clone to zip is easy

*Git installs kasini3000, which can be updated incrementally. Upgrading with msi and rpm is too expensive for incremental scripts

*In Tencent qq group (instant messaging software, similar to telegraph), There is a compressed package, about 70mb. If you want to give an email, I can send it to you.

### About the Linux installation path:
It cannot be changed temporarily.

### About the Win installation path:
It should never be changed. ' c: Program Files' has spaces, which is not conducive to command line programs.

**Comment by rhubarb-geek-nz** [comment]
On Linux/Posix/Unix systems /etc/ is used for local system configuration files. It is not a place for installing programs. For a cross platform solution /usr/share is traditional. For instance the Microsoft Packages for DotNET Core install in /usr/share/dotnet whereas Centos/Fedora etc install in /usr/lib64/dotnet. On Linux systems PowerShell is installed in /opt/microsoft/powershell/7. On MacOS it installs in /usr/local/microsoft/powershell/7/pwsh.

Changing files in /etc requires root access. A system for managing remote systems should not need root access on the local machine.

c:\Program Files has been the standard place to install programs on Windows for over 25 years. That is where everyone expects programs to be installed. C:\ProgramData should only be for data be shared amongst all users on the same machine.

PowerShell itself installs in "C:\Program Files\PowerShell\7" so it has no problems with spaces in paths.

MSI, RPM and DEB are not rarely available, they are the most common ways of deploying programs on Windows and Linux systems. There are some like ArchLinux that don't use RPM or DEB and a PKGBUILD should be written to support that platform. MSI, RPM and DEB all support well managed systems with versioning of packages and update in place.

If you are managing other systems then your scripts need to support spaces in filenames and paths, because that is what systems have. It may be tedious because escaping and quoting may be required but that is what you need to do to support general systems.

Doing a clone or a zip from git may be easy, but that does not make it the best way to install software on a non development machine.

**Comment by rhubarb-geek-nz** [comment]
On a Linux system, data that changes should live under /var/lib/. ( like /var/lib/docker, /var/lib/systemd etc )

**Comment by kasini3000** [comment]
Thanks for the discussion,Here's an English introduction:
https://www.cnblogs.com/piapia/p/16534765.html

*/etc/kasini3000 is shorter than/usr/share/kasini3000

*kasini3000, the master computer ,and the node computer basically need root 
permission. I don't think there is a question of authority.

*The Kasini 3000 is a great product. It has many problems, but not those you raised. Don't focus on small issues too much.
I think the things you think should be done will have a negative impact on the Kasini 3000. I don't think you have considered it carefully. 

You can try to use it on your way for 30 days, and then look at these questions again. see you 30 days later.

**Comment by rhubarb-geek-nz** [comment]
As a comparison, PowerShell release zips/tars and packages for each release. However they don't create ARM32 or ARM64 packages for Linux. So yes, you could unpack the tar.gz, but that is not the way to run a well managed system. It also makes it hard to track what is installed on your system because it is not listed as a package. Hence I repackage the ARM binaries from the tar.gz into a formal RPM,DEB or PKG so it can be installed and managed like any other package along with dependencies. It also means you can examine the package before you install it so you can have confidence about what and where things are being installed. [powershell packages for ARM](https://sourceforge.net/p/rhubarb-pi/wiki/pkg-powershell/)

**Comment by kasini3000** [comment]
This post will be closed. There are too many topics in it, which is not conducive to project management.
If necessary, please resubmit, **separate topic**,  topic one by one ，thank you.
