### ISSUE TITLE
Putty Security in kasini3000

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#12]
There are reports of Trojanized versions of PuTTY being distributed. These are versions of the original PuTTY but a backdoor has been added to the code.

For example: https://www.microsoft.com/security/blog/2022/09/29/zinc-weaponizing-open-source-software/

I notice that the git repository contains files such as psftp.exe and plink.exe which appear to be PuTTY programs.

How can we have confidence that the binary versions distributed by kasini3000 are not malicious versions?

**Comment by rhubarb-geek-nz** [comment]
OpenSSH client has been available directly from Microsoft on Windows 10 for a number of years. Is there any need PuTTY files in the repository?

**Comment by rhubarb-geek-nz** [comment]
kasini3000 also has copies of ssh.exe in lib/cwrsync/ssh.exe and master_script/kasini3000/git/usr/bin/ssh.exe

Given the plethora of ssh.exe, is plink.exe still needed?

**Comment by kasini3000** [comment]
> How can we have confidence that the binary versions distributed by kasini3000 are not malicious versions?

It's easy to determine if it's the original program. 
**Check the software signature on properties page of the right mouse button**  
or go to the official website to compare the sha256 value. 
I reiterate that there are currently no unsafe factors in putty.

**Comment by rhubarb-geek-nz** [comment]
I have full confidence in PuTTY itself, the problem is with the delivery mechanism. There is no validation of signatures automatically performed when plink.exe and psftp.exe ( or any binary ) is installed on the master system. So if your GitHub repository was compromised then so would every master and hence every node.

**Comment by kasini3000** [comment]
hi ,Corrected the easily ambiguous title.

**Comment by rhubarb-geek-nz** [comment]
The advantage of installing binaries using package managers is that they will validate the signatures on installation.
