### ISSUE TITLE
Project page says it supports Raspberry Pi but install refers to amd64

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#14]
Hi, project page says project supports Raspberry Pi.

When looking at zkj_install_powershell_从win主控机到linux被控机.ps1 it refers to amd64.

I see no references for either aarch64 or any 32 bit arm architectures.

What Raspberry Pi operating systems does it support?

Thanks.

**Comment by kasini3000** [comment]
### install kasini3000 master on raspberry linux arm: 

1 Manually install the raspberry pie version powershell:
https://github.com/PowerShell/PowerShell  ---> search  "Raspbian (Arm)"

https://learn.microsoft.com/en-us/powershell/scripting/install/install-raspbian?view=powershell-7.2


2 Manually copy 
/etc/kasini3000/cmdb/linux_arm？_SQLite.Interop.dll
to
/etc/kasini3000/cmdb/SQLite.Interop.dll
and overwrite

3 test sqlite sql if fine:
/etc/kasini3000/cmdb/cmdb_test.ps1

**Comment by rhubarb-geek-nz** [comment]
> 2 Manually copy /etc/kasini3000/cmdb/linux_arm？_SQLite.Interop.dll to /etc/kasini3000/cmdb/SQLite.Interop.dll and overwrite

Is that just 32 bit ARM? No aarch64 ?

**Comment by kasini3000** [comment]
Would you like to help find this library, this version? 
And tell me

**Comment by rhubarb-geek-nz** [comment]
> 2 Manually copy /etc/kasini3000/cmdb/linux_arm？_SQLite.Interop.dll to /etc/kasini3000/cmdb/SQLite.Interop.dll and overwrite

When system is update from Git will than then revert back to whatever SQLite.Interop.dll  originally was?

For instance, "0update_k记饭店_from_git.ps1" says to use "git reset --hard" to update

**Comment by rhubarb-geek-nz** [comment]
> Would you like to help find this library, this version?
> And tell me

Effectively yes. Because you have just provided the DLLs, we don't know what version they are supposed to be. So if you haven't provided a specific architecture, we have to work out what version it has to be to match your tested configuration, and where to get them from.

**Comment by kasini3000** [comment]
0update_k记饭店_from_git.ps1 
1incremental_update_kasini3000_from_git.ps1
only for win

raspberry only need ```git pull```  vast majority of cases

Next, I will write a raspberry pie installation and upgrade document in the docs directory.

**Comment by kasini3000** [comment]
en ,find out arm64 version of SQLite.Interop.dll,upload to here.

**Comment by rhubarb-geek-nz** [comment]
zkj_install_powershell_从linux主控机到linux被控机.ps1 this does not support arm32 or arm64.

The PowerShell Core team have not published any ARM powershell packages, only zip/tar.gz

**Comment by rhubarb-geek-nz** [comment]
https://gitee.com/chuanjiao10/kasini3000/blob/master/docs/install_kasini3000master_to_raspberry.md

Thanks
