### ISSUE TITLE
Suggestion - simplification of /etc/os-release matching

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#15]
There are 117 places in the scripts where /etc/*-release is attempted to be matched to determine the capabilities of the host operating system. 

The code could be greatly simplified by parsing ID and ID_LIKE just once and using those field values to determine host capability

Example code

```
$global:ID = [string]$null
$global:ID_LIKE = @()

foreach($line in [System.IO.File]::ReadLines("/etc/os-release"))
{
	$nameValue = $line.Split("=")
	if ( $nameValue.Length -gt 1)
	{
		switch ( $nameValue[0] )
		{
			"ID" { $global:ID = $nameValue[1].Trim().Trim('"') }
			"ID_LIKE" { $global:ID_LIKE = $nameValue[1].Trim().Trim('"').Split(" ") }
		} 		
	}
}

Write-Output ( "ID=" + $global:ID )

Write-Output ( "ID_LIKE=" + $global:ID_LIKE )
```

On AlmaLinux this then prints

```
ID=almalinux
ID_LIKE=rhel centos fedora
```

Then to determine if the system uses "deb" packages see if ID is "debian" or ID_LIKE contains "debian"

Likewise to determine if system uses "rpm" check for ID is "fedora" or "mariner" or ID_LIKE contains "fedora"

This would greatly simplify the code in those cases.

**Comment by kasini3000** [comment]
test all os in c:\ProgramData\kasini3000\linux_distribution_check.ps1
You will find problems with your code.
do it

**Comment by rhubarb-geek-nz** [comment]
These look like what I would expect

AlmaLinux 9

```
ID=almalinux
ID_LIKE=rhel centos fedora
```

Centos 8

```
ID=centos
ID_LIKE=rhel fedora
```

Ubuntu 22.04

```
ID=ubuntu
ID_LIKE=debian
```

Rasbian 11

```
ID=raspbian
ID_LIKE=debian
```

Oracle Linux 9

```
ID=ol
ID_LIKE=fedora
```

CBL-Mariner 2.0

```
ID=mariner
ID_LIKE=
```

Rocky 9

```
ID=rocky
ID_LIKE=rhel centos fedora
```

RedHat 9

```
ID=rhel
ID_LIKE=fedora
```

Debian 11

```
ID=debian
ID_LIKE=
```

**Comment by rhubarb-geek-nz** [comment]
This has the advantage that you can work with operating systems you have not seen before but can detect something familiar in ID_LIKE

If there are known exceptions which don't follow the rule you can still test for them the old way.

**Comment by rhubarb-geek-nz** [comment]
And Fedora 36

```
ID=fedora
ID_LIKE=
```

**Comment by rhubarb-geek-nz** [comment]
Certainly there are more packaging mechanisms, eg Alpine with apk and ArchLinux with its own format, I am not saying that rpm and deb are the only formats. What I am saying is you can group operating systems by capability and features rather than having to code for each specific version in every case, where in 90% of the time it is duplication of code used in a similar case.

**Comment by rhubarb-geek-nz** [comment]
Does it really matter if something is "Hunting Beagle" or "Soaring Falcon" or whether it uses rpm and yum?

**Comment by rhubarb-geek-nz** [comment]
If you do need unique identifiers then grab the VERSION_ID as well.

**Comment by rhubarb-geek-nz** [comment]
alpine 3.15

```
ID=alpine
ID_LIKE=
```

**Comment by rhubarb-geek-nz** [comment]
Amazon Linux 2.0

```
ID=amzn
ID_LIKE=centos rhel fedora
```

**Comment by rhubarb-geek-nz** [comment]
Kali

```
ID=kali
ID_LIKE=debian
```

**Comment by rhubarb-geek-nz** [comment]
Arch Linux

```
ID=arch
ID_LIKE=
```

**Comment by rhubarb-geek-nz** [comment]
openSUSE Leap 15.4

```
ID=opensuse-leap
ID_LIKE=suse opensuse
```

**Comment by rhubarb-geek-nz** [comment]
openSUSE uses zypper so no issue that it does not say fedora even though it uses rpm

I am happy with that set of tests. I don't have access to the other cloud providers.

**Comment by kasini3000** [comment]
1 I am happy to see someone help the code become better. Your idea is good.

2 Your code is negative and harmful. Lacking deep consideration. Explain to you that this is a waste of my time.

3 Specifically, these codes must be independent segments. This makes it easy to add and delete any paragraph.

Each piece of code must be able to work independently, and it is used to determine the unique distribution, and version. 
Take oracle as an example, you must distinguish oracle linux 7, or 8, or 9
The distribution does not necessarily use an os-release file, which may be "xxx-release".

So,"id","id like", almost useless.

You used to want to use "id like" to determine whether to use the package manager.
As you know some "id like" is empty now, That code can't succeed

try use bkj_install_linuxpackage.ps1 on kaili ,arch, test "switch os ,default" code work.

**Comment by rhubarb-geek-nz** [comment]
Lets take Oracle as an example as you suggest

Versions 7.9, 8.6, 9.0 all have

```
ID="ol"
ID_LIKE="fedora"```

In their /etc/os-release

And all use rpm package format and can use yum to manage.

Its a matter of coding style, I prefer to reuse code rather than duplicate code.

Not having independent paragraphs means you don't have to keep changing the code every time you want to support a new operating system version.

Less code means less code to maintain. 

Don't reinvent wheel, use wheels that already exist

**Comment by rhubarb-geek-nz** [comment]
> try use bkj_install_linuxpackage.ps1 on kaili ,arch, test "switch os ,default" code work.

If kali works with no changes in the default case when why do you need all the extra code to handle debian and ubuntu? Why would they not also work in the default case?

**Comment by rhubarb-geek-nz** [comment]
> You used to want to use "id like" to determine whether to use the package manager. As you know some "id like" is empty now, That code can't succeed

So my code works when ID_LIKE is empty. The code leaves ID_LIKE as an empty list. So when you follow the rules I suggested, for example ID="debian" OR ID_LIKE contains "debian", then if the list is empty then it does not contain "debian".

That is not the case failing, that is working as designed, you have successfully tested that the system is not claiming to be like "debian"

**Comment by rhubarb-geek-nz** [comment]
If you have to change the code every time a new version of operating system comes out then users of the project also have to keep updating their project to keep it working. If you can handle the code so it does not care about the specific version of operating system or even the name of the distribution then you don't have to keep changing your code every time a user wants to use a system you have never heard of.

**Comment by rhubarb-geek-nz** [comment]
Here for example is working shell script that uses ID and ID_LIKE to determine the best version of PowerShell to try and use on an unknown system. It is to demonstrate the principle in existing working code.

```
for d in $ID $ID_LIKE
do
	echo Looking for $d

	SRCPKG=

	case "$d" in
		debian | ubuntu )
			ARCHORIG="amd64"
			SRCPKG="${PACKAGE}${USCORE}${VERSION}-1.deb${USCORE}${ARCHORIG}.deb"
			;;
		centos | rhel | fedora | mariner )
			ARCHORIG="x86_64"
			SRCPKG="${PACKAGE}-${VERSION}-1.rh.${ARCHORIG}.rpm"
			;;
		* )
			;;
	esac

	if test -n "$SRCPKG"
	then
		if wget "${REPOS}/${SRCPKG}"
		then
			break
		fi
	fi
done
```

That uses ID first, and then the ID_LIKE in sequence until it finds a match. Yes it only covers "deb" and "rpm", but then so does the PowerShell project.

https://sourceforge.net/p/rhubarb-pi/code/HEAD/tree/trunk/pkg/powershell/package.sh#l106

**Comment by rhubarb-geek-nz** [comment]
In that script, for example, it use an RPM for "fedora" because ID="fedora", and uses RPM for "rocky" "almalinux" and "ol" because their ID_LIKE all contain "fedora"

**Comment by kasini3000** [comment]
### A：
1 Code snippets must be separated into independent ones. The idea of combining code snippets is unacceptable. If you think the combination is better, modify the script and use it yourself.
2 For the independent code segment, you must ask which script name and what specific function problems exist in the existing code.
