### ISSUE TITLE
Suggestion - Package Kasini3000 as an MSI

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#18]
Packaging Windows software as an MSI is the standard way to deliver software in managed environments.

It can be installed simply from Explorer or using msiexec. It can be easily removed using "Add and Remove Programs" and msiexec.

With well managed curation of the content in the MSI it can be under 20MB.

With a proper software release cycle you can produce an MSI for each version. 

Visibility in "Add and Remove Programs" means the user is aware what is installed.

**Comment by rhubarb-geek-nz** [comment]
The MSI should be created as part of a release cycle with formal versions.

Packages should by signed with a code signing certificate

MSI packages can be published at [Windows Package Manager](https://learn.microsoft.com/en-us/windows/package-manager/package/)

Once a package is published at the Windows Package Manager then installing is simply a matter of

```
winget install kasini3000
```

Windows Package Manager can also be used to update installed packages.

**Comment by kasini3000** [comment]
duplicate #1 
hi Do not submit questions repeatedly.

The installation principles of the kasini3000 are:
unzip then use or git clone then use.
For the time being, it is not considered to distinguish between Windows and Linux versions. And making the installation package.

**Comment by rhubarb-geek-nz** [comment]
> This post will be closed. There are too many topics in it, which is not conducive to project management.
> If necessary, please resubmit, **separate topic**, topic one by one ，thank you.

I did exactly what you suggested.
