### ISSUE TITLE
dpkg lock files are deleted

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#19]
The purpose of the dpkg lock files is to protect the integrity of the package management system.

The sequence "rm -rf /var/lib/dpkg/lock;rm -rf /var/lib/dpkg/lock-frontend;" occurs in multiple places.

This is not good practice and risks corrupting the package management system and preventing normal operating system updates.

**Comment by kasini3000** [comment]
by design

**Comment by rhubarb-geek-nz** [comment]
> by design

Not a good design, then.
