### ISSUE TITLE
Suggest don't include binary files in a source code repository

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#2]
Binary files don't belong in a source code repository.

For example it looks like EXE and DLL from Cygwin are in https://gitee.com/chuanjiao10/kasini3000/tree/master/lib/cwrsync
 
If you use 3rd party components or projects then reference the original source for that component and make it a dependency.

**Comment by kasini3000** [comment]
1 are you kasini3000 user？are you install and use it ? ---I will not consider the needs of non users for the time being

2 What practical inconvenience does it bring to you?

3 Generally speaking, developers have the right to make their own project directory planning, which does not affect the use.
Developers are required to change the directory planning, which belongs to customized development. Only major customers are considered.

try to say what you will do.Are you willing to pay for this change? How much do you plan to pay $ ?

**Comment by rhubarb-geek-nz** [comment]
I am not a user of it yet, I was invited to take a look at the project so before I install it I was looking at what was going to be installed. Following the installation instructions I saw that one was supposed to clone the repository into the /etc directory, so I looked to see what was going to be installed there. As a Linux user I was not expecting to see Windows EXE and DLL being installed in the the /etc directory. As a Linux user my expectation was an installation would only include the files required for that platform.

**Comment by kasini3000** [comment]
A voice in my head told me that /etc/nginx/nginx.conf contains if regular code, so I can use it ps1 file As a configuration file, placed in/etc/kasini3000. 
If someone asks, I will say that it is a configuration file. My binary file "pwsh", is not in it.

A voice in my head also told me that users who are picky should serialize binary files into text and store them in/etc/kasini3000
This fully complies with /etc's limit of saving configuration files only.
Use another ps1 script to extract it into /usr/bin according to the OS, 
but this undoubtedly adds a lot of work.He let me wait. 

A voice in my head told me that the chef of a five-star hotel knelt down on one leg and offered me a big meal. 
He asked me to find out the problem in meal and give me 100 million $

i only has intel cpu ,why amd code in my linux kernel file?
Is it weird that in a cross-browser html, there is specific code for each browser? It's just put together and not separated,
In a cross-platform program, some code is specially developed for an os, is it strange?

**Comment by rhubarb-geek-nz** [comment]
It depends what direction you want the project to take. At the moment it looks like a lot of potentially useful powershell scripts in git repository, but not a packaged product. My suggestions are about how to take it to the next level so it is a well-packaged versioned product that is easy and consistent to install, update and remove on an end user's machine and only contains what is required for each target environment.

**Comment by kasini3000** [comment]
kasini3000 is Open source, free, cross-platform
Real users focus on being better to use than ansible.

**Comment by rhubarb-geek-nz** [comment]
I did some stats. A clone of the repository takes 322MB of disk space. Of that...

2MB is PowerShell scripts
57 MB of exe files
57 MB of dll file
170 MB of .git directory

So following the installation instructions, a Linux user has to install 322MB in order to use 2MB of PowerShell scripts.

**Comment by kasini3000** [comment]
pwsh can use dll on linux. 
eg: sqlite ,kasini3000 use powershell module of the cross-platform,sqlite also supports arm cpu.This is a feature of .net core.


Dll files cannot be run on Linux - why such a naive idea?
```
find /opt -iname '*.dll'
```

**Comment by kasini3000** [comment]
# about install package.

* to get install package: clone to zip.

* ANSIBLE use rpm,deb package.Its disadvantages are:
 [ ] The server is required, which requires payment.
 [ ] It is troublesome to import the gpg key.
 [ ] Cannot update incrementally.
The Kasini 3000 has no such shortcomings.

* ANSIBLE only for linux，kasini3000 for win,linux.
So the kasini3000 zip package can ones unzip,run anywhere.
All files are put together, just as the Linux kernel also contains amd code for intel cpu users .
