### ISSUE TITLE
Question - how do we tell what version of the project we are using

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#20]
The README mentions "3.1 alpha 1"

How do we know what version we have installed or are available?

The repository at https://gitee.com/chuanjiao10/kasini3000 has no tags so we can't tell what version from the repository.

What is the intended release cycle? Is this intended to be a rolling release with no versions? 

What is the process to ensure only good releases are used by "1incremental_update_kasini3000_from_git.ps1" on the client?

**Comment by rhubarb-geek-nz** [comment]
I have found https://gitee.com/chuanjiao10/kasini3000/blob/master/kasini_version.ps1

Which effectively means commit "5155d4270019dd5e3072331633ff32c3b39e8d8e" is "V3.2---ga2"

It would be useful to add tags to git to indicate the versions

**Comment by rhubarb-geek-nz** [comment]
Output of [kasini_version.ps1](https://gitee.com/chuanjiao10/kasini3000/blob/master/kasini_version.ps1) may be amusing but it does not make it easy for automated tools to determine what version is installed.

**Comment by kasini3000** [comment]
Congratulations on finding the answer.
release notes at wiki --->news, version number change in it.
