### ISSUE TITLE
Question - what is the process for backing up master keys and CMDB?

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#21]
Machines will have hardware failures. 

What is the recommended process for backing up and restoring both the SSH keys and CMDB on the master?

I have found that even if I created keys before running kasini3000 it would regenerate new ones over the top.

**Comment by kasini3000** [comment]
Kasini3000 uses dual ssh keyfiles. It is better to back up two public and private keys. Only one can be backed up, but it is not recommended.
At least, backup /root/kasini3000. There is 1 public key+1 private key. There is also the database of Kasini 3000.

**Comment by rhubarb-geek-nz** [comment]
> At least, backup /etc/kasini3000. There is 1 public key+1 private key. There is also the database of Kasini 3000.

I thought the keys and CMDB were in /root/.ssh and /root/kasini3000

**Comment by rhubarb-geek-nz** [comment]
We would we need to backup /etc/kasini3000 when it is just the contents of the git repository?

**Comment by kasini3000** [comment]
Oh, sorry. It's at /root/kasini3000. I was wrong.
