### ISSUE TITLE
Suggestion - Use Docker part two

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#23]
The responsibility and management of the SSH keys is left to the user, options include, but are not limited to

- Mount the keys directly in a docker volume
- Mount a host system directory directly as a volume for the keys
- Load the password protected private key from an external source and unpack within container
- Use a wrapping key on the private key file from external source and unwrap within container
- Use secure cloud service to provide keys, for example Azure Vault or AWS KMS
- Use ssh-agent to manage the keys
- Hardware device such as YubiKey

**Comment by kasini3000** [comment]
Good suggestion. In the future, consider completing these step by step.

**Comment by kasini3000** [comment]
hi all:
Don't expect kasini 300 to run in the container soon.
*The container brings troubles to the use of the kasini 3000.
*The container brings a false sense of security to the kasini 3000.
*Hosts outside the container, I mean the Linux kernel, openssl, etc., still have security problems. I think the best solution to these problems is alpine linux. It supports livecd and can upgrade the kernel by downloading new iso.

**Comment by rhubarb-geek-nz** [comment]
> *The container brings troubles to the use of the kasini 3000.

Are you saying that kasini3000 cannot be used in the cloud to manage vm nodes?

**Comment by rhubarb-geek-nz** [comment]
Updated [Dockerfile](https://github.com/rhubarb-geek-nz/kasini3000/blob/main/docker/Dockerfile) to use alpine:3.16

Size of image down to 237MB from 369MB with the original Microsoft PowerShell on Jammy Jellyfish

**Comment by rhubarb-geek-nz** [comment]
Unfortunately not able to run with "--read-only" in order to use a read-only filesystem.

```
Failed to create CoreCLR, HRESULT: 0x80004005
```

https://github.com/dotnet/runtime/issues/9336

**Comment by rhubarb-geek-nz** [comment]
[Dockerfile.ubuntu](https://github.com/rhubarb-geek-nz/kasini3000/blob/main/docker/Dockerfile.ubuntu) supports arm, arm64 and x64. It downloads the appropriate PowerShell architecture and compiles the SQLite.Interop.dll
