### ISSUE TITLE
Chain of custody is broken for SQLite interop dlls

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#24]
> It's easy to determine if it's the original program. **Check the software signature on properties page of the right mouse button** or go to the official website to compare the sha256 value.

The version of System.Data.SQLite.dll is 1.0.112.0.

This is not listed at https://www.sqlite.org/download.html or https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki.

I finally tracked it down to https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netStandard20-binary-1.0.112.0.zip

```
unzip -l  sqlite-netStandard20-binary-1.0.112.0.zip
Archive:  sqlite-netStandard20-binary-1.0.112.0.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   351744  2019-10-27 06:31   System.Data.SQLite.dll
    12492  2019-05-15 00:31   System.Data.SQLite.dll.config
   117056  2019-10-27 06:31   System.Data.SQLite.pdb
  1094797  2019-10-27 06:31   System.Data.SQLite.xml
---------                     -------
  1576089                     4 files
```

The files sizes match and so does the SHA256 for System.Data.SQLite.dll.

I was unable to find the interop dlls. The closest I could find was the NuGet package which is 1.0.103.0

https://www.nuget.org/packages/SQLite.Interop.dll/

The version included in the project is 1.0.111.0.

Where do the interop dlls come from? Thanks.

**Comment by kasini3000** [comment]
SQLite.Interop.dll source?
perhaps at
https://www.nuget.org/packages/Stub.System.Data.SQLite.Core.NetStandard/

**Comment by rhubarb-geek-nz** [comment]
> SQLite.Interop.dll source?
> perhaps at
> https://www.nuget.org/packages/Stub.System.Data.SQLite.Core.NetStandard/

Or perhaps not.

It only goes back to 1.0.115.0
