### ISSUE TITLE
Recommend consistent use of $global:kasini3000_data_path

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#25]
I see that a global variable is used to hold the data path.

```
$global:kasini3000_data_path = "/root/kasini3000"
```

and 

```
$global:kasini3000_data_path = "${env:USERPROFILE}\Documents\kasini3000"
```

This is good and aids portability between Linux and Windows.

There are 37 other occurrences where /root/kasini3000 has been hard-coded. For example

```
Remove-Item -Path '/root/kasini3000/ssh_key_files_old2/*'
```

These should be replaced with the variable and hence make the scripts more consistent and portable.

**Comment by kasini3000** [comment]
duplicate #6
