### ISSUE TITLE
k-sshfs-copy-a-file.ps1 refers to /etc/kasini3000/ssh_key_files_old1/authorized_keys

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#26]
Is this correct?

```
/usr/bin/scp /etc/kasini3000/ssh_key_files_old1/authorized_keys root@${目的ip地址}:/root/.ssh/
```

I thought the key files were in the data directory

```
/root/kasini3000/ssh_key_files_old1
```

Effectively, the /etc/kassini3000 directory is really the program directory which should be treated as read only.

**Comment by kasini3000** [comment]
```
k-sshfs-copy-a-file.ps1
ts推送主控机公钥到被控机_linux2linux_pwd.ps1
```

Warning: This script will be discarded (deleted)

reason:
Almalinux8.6, openeuler22.03, cannot be installed in. 
The official website will not be updated: https://github.com/libfuse/sshfs/releases

**Comment by kasini3000** [comment]
fixed on next update
