### ISSUE TITLE
bkl_install_linuxpackage.ps1 and bkj_remove_linuxpackage.ps1 simplifications and improvements

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#3]
Hi,

I had a look at [bkj_install_linuxpackage.ps1](https://gitee.com/chuanjiao10/kasini3000/blob/master/node_script/bkj_install_linuxpackage.ps1) and [bkj_remove_linuxpackage.ps1](https://gitee.com/chuanjiao10/kasini3000/blob/master/node_script/bkj_remove_linuxpackage.ps1) and have some recommendations.

The identification of the platform would be improved by focusing on the ID and VERSION_ID fields in /etc/os-release rather than current pattern matching. Many of the patterns in the code don't match this record of existing [/etc/os-release](https://sourceforge.net/p/rhubarb-pi/wiki/etc-os-release/) files.

There is a lot of code duplication between the two programs that I am sure could be shared.

It would also be simplified by identifying the package API type by operating system and using common routines rather than a function per operating system version.

There are question-marks around Amazon Linux in the code. ID="amzn" VERSION_ID="2" uses yum and rpm.

I don't know why there are "Start-Sleep" in the code or why you are trying to force delete the /var/lib/dpkg/lock* files. They are there for a reason and one should leave the operating system itself to manage its synchronisation and protection of the repository database files.

Some parts of the code use sudo, and other lines immediately next to them don't even though using a command that needs root access, eg the ubuntu cases in bkj_remove_linuxpackage.ps1

Apart from the exit 1 if the operating system is Windows, the scripts have exit 0 at the end. How does the caller know if they were successful?

**Comment by rhubarb-geek-nz** [comment]
Also in /etc/os-release if you don't recognise the ID value you can try the list in ID_LIKE.

**Comment by rhubarb-geek-nz** [comment]
Not sure if you are doing this, but setting environment variable DEBIAN_FRONTEND=noninteractive while running apt commands can prevent them trying to do manual configuration following installation.

**Comment by kasini3000** [comment]
Give it a test, or you may not understand why.
1. What are the problems when using it in a real environment?
2 Can you try to analyze the reasons? To help improve the program.

----

install_package script has been improved several times, but there is still a problem.

The current problem is to improve the script code that needs to be processed because the ubuntu key has expired.

The difficulty of this problem is that the name of the apt package containing the new key is unknown.
Can you provide a solution?

**Comment by rhubarb-geek-nz** [comment]
I don't understand why, that is why I am not going to actually run it. I don't run software I don't understand or trust as root just to see how it behaves. 

What I am doing is a code inspection to try and understand the code first and hence asking questions about parts that don't look right. That is all part of open-source and a thousand eyes that can look at the actual code. 

I see code that is intending to delete file locks that protect the packaging system and I don't think it should be doing that and don't want it do that on my system. So I am asking why. If there is a good reason then an explanation of why could be added to the source code as comment.

Likewise I see that it always returns exit 0, hence my question how one is supposed to know if the operation failed.

SimilarlyI don't know why the code has a Start-Sleep in it. I don't see that as a security risk, but also I don't understand why it is there.

Both the scripts to install and remove packages look far more complicated than they need to be. The code could be ten times smaller.

As I mentioned, the existing patterns trying to determine the operating system don't match real world examples of [/etc/os-release](https://sourceforge.net/p/rhubarb-pi/wiki/etc-os-release/). For example 'Rocky Linux release 8' 'Rocky Linux release 9' 'AlmaLinux release 8' 'AlmaLinux release 9'. 

Rather than having all those tests for specific cases you could look for the ID and ID_LIKE to determine the packaging mechanism. Then all you need to do is check for "debian" to see if it used "deb" packages, and "mariner" or "fedora" to determine if it uses "rpm" etc, and hence you would have known that Amazon Linux 2 uses "rpm" because it has "fedora" in the ID_LIKE.

If you already know the system is a "debian" type system, then there is no need to call "which yum" or "which dnf" etc.

I notice it does not support openSUSE and zypper, although this uses "rpm" it is not like "fedora" and uses zypper for package management.

**Comment by rhubarb-geek-nz** [comment]
Can you describe the ubuntu problem? What key are you referring to?

Do you know the thumbprint of the key that is missing?

Have you tried the ubuntu key server?

For example

`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
`
