### ISSUE TITLE
Suggestion - compiling SQLite.Interop.dll ARM64 Linux

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#32]
As far as I can tell, the SQLite.Interop.dll is the only native compiled component required for Kasini3000 ( apart from the correct PowerShell binaries being installed )

If you want to compile the matching SQLite.Interop.dll for ARM64 then you can get the 1.0.112.0 source from

https://system.data.sqlite.org/blobs/1.0.112.0/sqlite-netFx-source-1.0.112.0.zip

To build this on ARM64 Linux, unpack the zip in an empty directory and 

```
cd Setup
bash ./compile-interop-assembly-release.sh
```

The result should be in

```
bin/2013/Release/bin/SQLite.Interop.dll
```

**Comment by rhubarb-geek-nz** [comment]
Need an Alpine build or ARM64?

I have set up a [build script](https://github.com/rhubarb-geek-nz/SQLite.Interop/tree/1.0.112.0) that automates the building and built [compiled versions](https://github.com/rhubarb-geek-nz/SQLite.Interop/releases/tag/1.0.112.0) for common Linux RID.

Checkout tag "1.0.112.0" and use release "1.0.112.0" to match what kasini3000 currently has.

**Comment by kasini3000** [comment]
It is better to have a successfully compiled file: SQLite.Interop.dll
I expect someone to compile it and keep updating it.
At present, I am looking for such projects...

**Comment by rhubarb-geek-nz** [comment]
> At present, I am looking for such projects...

https://github.com/rhubarb-geek-nz/SQLite.Interop and https://github.com/rhubarb-geek-nz/SQLite.Interop-win

**Comment by kasini3000** [comment]
Now integrated into the Kasini3000 project:
https://gitee.com/chuanjiao10/kasini3000/blob/master/cmdb/linux_arm64%EF%BC%9FSQLite.Interop_readme.txt
Thank you very much!

this issue fixed and cloes.
