### ISSUE TITLE
Suggestion - please put tags on the git repository

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#33]
Hi, you have a version history at https://gitee.com/chuanjiao10/kasini3000/wikis/news

But this is hard to match against the git repository using standard tools and for non Chinese readers.

Can you put git tags on the commits that match the formal releases? I recommend tags in plain ASCII with the simple release version.

This would make it easier for all users of your git repository to see the formal release history and allow tools to clone specific releases.

Cloning the whole repository, stepping through the git log and trying to parse kasini_version.ps1 is not very efficient.

It will make the git repository look well managed for a product with formal releases.

Thanks,

**Comment by kasini3000** [comment]
Currently, there is no release, so there is no tag.
I haven't seen any benefits for the time being, which only adds negative complexity.
