### ISSUE TITLE
Alpine bash is at /bin/bash

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#34]
Normally the path for bash is /bin/bash just like /bin/sh

Can you not use normal PATH resolution for bash?

```
/usr/bin/bash: /etc/kasini3000/gx更新主控机ssh秘钥2z.ps1:129
Line |
 129 |  "@ | /usr/bin/bash
     |       ~~~~~~~~~~~~~
     | The term '/usr/bin/bash' is not recognized as a name of a
     | cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify
     | that the path is correct and try again.
```

**Comment by rhubarb-geek-nz** [comment]
In terms of coding style, can you remove the need for a pipe?

Can

```
			@"
ssh-keygen -t rsa -b 4096 -N '' -f '${global:kasini3000_data_path}/ssh_key_files_old1/id_rsa'
"@ | /usr/bin/bash
```

be changed to something like

```
			bash -c "ssh-keygen -t rsa -b 4096 -N '' -f '${global:kasini3000_data_path}/ssh_key_files_old1/id_rsa'"
```

And to execute that, does it actually need to be bash? Why not simply sh?

**Comment by kasini3000** [comment]
gx更新主控机ssh秘钥2z.ps1
jl建立主控机ssh秘钥1z.ps1
run_linux2linux_key_pwd.ps1
u库定时任务_建立任务计划_linux.ps1
zkj_s所有linux被控机改密码_验证周期_改密码_验证_对调密码_写入时间戳.ps1

up files hard code to /usr/bin/bash,
For compatibility with alpine, kasini3000 update code to use "/bin/ash" on next update.
