### ISSUE TITLE
Copy of Git included in repository

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#4]
Why is there a full copy of git in the repository when in order to install the code you already needed git installed to do the installation?

**Comment by kasini3000** [comment]
git tool lib for win is from github

https://github.com/git-for-windows/git/releases/download/v2.35.3.windows.1/MinGit-2.35.3-64-bit.zip

(url will change via tool version number update. )

When promoting kasini3000 in Tencent group, I will provide zip package. With git tool lib, Windows users can update incrementally through this script:
c:\ProgramData\kasini3000\1incremental_ update_ kasini3000_ from_ git.ps1

### A: Users of kasini3000 windows do not need to install git for win in advance.

**Comment by rhubarb-geek-nz** [comment]
If you update the version of git.exe in the repository, how does git.exe update itself while it is running? Normally Windows prevents programs from being updated while they are running. Does this work?

So Linux users who follow the installation instructions now have three copies of git, the native one plus two useless Windows versions, one in /etc/kasini3000/master_script/kasini3000/git, and one encoded within the /etc/kasini3000/.git directory. Then if you update it for Windows users, Linux users will then have four copies as there will now be two copies of the binaries in /etc/kasini3000/.git

**Comment by kasini3000** [comment]
> The .git directory will grow over time

You can't have it both ways.
All projects based on git source code that can be incrementally updated by git have this problem.
What would you recommend?

**Comment by kasini3000** [comment]
I'd like to know your opinion on this issue:
Free fish in the river, give you fish head, fish gills, fish floats, but you don't need those things, you just need fish meat, even spices you don't want.
But cooked fish is very expensive, and cooking fish requires costs.

So , what is you choose?:
1 Tolerance of free fish.
2 Use money to buy your favorite finished fish and meat.
3 Do everything by yourself: let yourself become God, and design a kind of boneless, delicious fish that does not need cooking.

**Comment by rhubarb-geek-nz** [comment]
I would recommend not storing binary executables in Git. Git is absolutely great for storing source code as text, then it only needs to store the difference between each commit, what lines actually changed. So the .git directory only grows line by line.
For binary files it stores a complete copy of each new version of the file. So for graphical images such as png you get complete copies in .git directory.
My recommendation is to not use Git as a delivery mechanism for software to end users. When you create a release, I suggest you create platform specific software packages for each release that only contain the binaries for that target system.
Git is already available from many sources for Windows. You don't need to package and provide it again.

**Comment by kasini3000** [comment]
Well, I know your point.
My answer is: this proposal will not be accepted.
-----
I find your suggestions are all negative. This suggestion affects the automatic update of Windows users.
The priority is easy development, easy installation and easy upgrade.
Instead of reducing disk space, or making development and deployment more difficult.

**Comment by rhubarb-geek-nz** [comment]
Now you could have the best of all worlds by....

Using existing packaging manages to manage GIt etc, already done on Linux, but on Windows you could use "winget", "Homebrew" or "Chocolatey" to manage the updating of Git and PowerShell Core. Those already exist.

Then your repository would only need to store your PowerShell scripts, they currently total around 2MB. 

So lets say you used the Git repository just for your scripts and let the package managers do there job. So end users still use Git to clone your repository to get the PowerShell scripts and can update them with "git pull".

Then everyone would win, you don't have to manage updates for Git executables, the total repository size would only be a few megabytes even after many changes to your scripts, and Linux users aren't having to download Windows binaries.

**Comment by kasini3000** [comment]
Please try to analyze the advantages and disadvantages of doing this.

**Comment by rhubarb-geek-nz** [comment]
Pros
===
Package managers are good at installing and updating software.
Small installation size on end user system
You don't have to concern yourself with what version of Git or PowerShell needs to be installed
You can focus on your project and your scripts
Updates will be quicker because they will be smaller
Users don't need to download binaries that don't run on their system

Cons
===
You would need to create a new repository to hold just the scripts
The installation instructions would be different

**Comment by kasini3000** [comment]
Tools need to be simple, easy and easy to use. You don't know how to make a tool. 
In order to reduce space, the increased user complexity cannot be tolerated.
Simply copy, and you can switch the OS between Windows and Linux at will,
It's a bit like Java, it's a bit like an automatic car.

Your idea is very bad, very negative.It cannot be automated or used out of the box.

**Comment by rhubarb-geek-nz** [comment]
Can you update git.exe while running the same git.exe that you want to update on Windows?

**Comment by kasini3000** [comment]
Free fish in the river, give you fish head, fish gills, fish floats, but you don't need those things, you just need fish meat, even spices you don't want.

You will never buy watermelon. Because 10 kg watermelon has 2 kg skin.

**Comment by rhubarb-geek-nz** [comment]
> You will never buy watermelon. Because 10 kg watermelon has 2 kg skin.

The installation is not 20% bigger than it needs to be, it is 16,000% bigger than it needs to be.

**Comment by rhubarb-geek-nz** [comment]
> Your idea is very bad, very negative.It cannot be automated or used out of the box.

If only there was some easy to use automation tool or scripting system that could be used on Windows to install software and perform systems management.
