### ISSUE TITLE
Suggest kasini3000.service uses onCalendar rather than RestartSec

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#5]
You have a systemd service to invoke u_db_crontab.ps1 

u_db_crontab.ps1  contains test for the the value of minutes before performing certain tasks.

You could use the onCalendar systemd timer mechanism in order to simply run scripts at scheduled times rather than programmatically trying to determine the time.

Likewise on Windows one can use scheduled tasks for the equivalent mechanism.

**Comment by kasini3000** [comment]
c:\ProgramData\kasini3000\master_script\kasini3000\kasini3000.service
This file for linux master ,fo SYSTEMD, Is it you want ?

**Comment by rhubarb-geek-nz** [comment]
Yes that is what I was looking at. It runs [u_db_crontab.ps1](https://gitee.com/chuanjiao10/kasini3000/blob/master/u_db_crontab.ps1)

It looked like a complicated way to solve a problem that was already solved. 

As far as I can determine it is a script that determines what script to run at what time. 

That is exactly what traditional crontab or systemd timers already do. Likewise scheduled tasks on Windows.

**Comment by kasini3000** [comment]
With script and sqlite database, a master based scheduled task engine is implemented.
The feature is to support 67 minute cycle.
High availability of dual computers is supported based on heartbeat. Dual computers can be cross platform Windows, Linux,
The main control machine task plan based on multiple processes and one thread per process is provided,
The main control machine task plan based on multiple processes and multiple threads for each process is provided,

I still can't understand the point of this issue

**Comment by rhubarb-geek-nz** [comment]
It was a suggestion because it looked like a duplication of capability that was already provided by the host operating system.

The code itself has lots of conditionals based on host platform and time, and starting different tasks at different times depending on operating system.

My thought was this was not needed and you could use scheduled tasks and systemd timers to run those programs directly at those scheduled times.

**Comment by kasini3000** [comment]
> It was a suggestion because it looked like a duplication of capability that was already provided by the host operating system.

To some extent, this is repeated wheel building. Because it is necessary to provide the task plan of cross platform 2 master computers.
Heartbeat based data synchronization,
It has multiple processes, multiple threads, and can be controlled by config.ps1.
Windows, Linux, and ansible do not have these.
