### ISSUE TITLE
kasini3000.service should run tasks as non-root user

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#6]
As far as I can tell kasini3000.service is running u_db_crontab.ps1  as root.

It is best practice to run services as a non-root user and then only use sudo or set-uid in order to invoke limited functions that require root access.

A master node should not need to run anything as root on the master node while it is administering child nodes. The cases for running sudo should be limited to the single command required to perform the administration on the target system.

Running as non-root is best practice because it means that errors or misconfigurations in your application are much less likely to affect the rest of the system. It also provides less opportunity for your application to be inadvertently turned into a backdoor.

Postfix, apache, tomcat, systemd itself and many other well-behaved applications don't run the services as root.

While kasini3000 could be run within a docker container it would be without systemd, and if running as root within the docker it could still corrupt the files within the container due to misconfiguration or programming error.

**Comment by kasini3000** [comment]
> A master node should not need to run anything as root on the master node while it is administering child nodes. 

Can you try to talk about any specific security risks?

I think: without root permissions, then kasini3000 doesn't work, which is **more secure**.

In 2022, there will be a huge increase in linux hacking programs, and many linux servers will be breached. Among them, root is broken less than ordinary users.

Suppose a hacker breaks through a linux with ordinary user privileges and uses it to execute kasini3000 to control multiple broilers. This makes me even less want to see.
Could you understand me?

So, think again:
What are the disadvantages of executing kasini3000 with root privileges?
What are the disadvantages of executing kasini3000 with non-root privileges?
Best to have real evidence.
or
Open a discussion thread and hear what others have to say on the powershell team, or the powershell forum ?

**Comment by rhubarb-geek-nz** [comment]
The principle is that any job on Unix should run with the least privileges in order to perform its role. The advantage is that then if there is a bug in the software or misconfiguration then when something goes wrong the least damage is done. Root on UNIX is incredibly powerful and will happily write over or delete your file system if you tell it to. So the purpose of not running as root is that if, due to an error in execution, it starts trying to do things it should not do then it can't because the process does not have the rights to do that.

As an example, a process creates a temporary directory, performs some work and then at the end of the job deletes the directory and its contents. All straight forward. Now imagine that during execution an error occurs due to, say the file system becoming full and unable to write files, or the job is mistakenly run twice using the same directory, when the job comes to clear up and it tries to change directory to where the temporary files are the directory is gone. When it comes to the clear up job it may attempt to change directory, that fails but it happily continues and deletes all the files in the current directory whatever that directory happens to be. Now if the program was running as a user with limited access the worst if could do is delete its own files. In the case of root it could happily wipe the entire filesystem.

So lets say kasini3000 is running as root and never has a bug and is never misconfigured, and always checks every return code and has been tested in all conditions including file system becoming full. How did kasini3000 get there? Who installed it as root? Is there now no SSH access to the host and no user is able to log into the system to administer it? How is it updated?

**Comment by kasini3000** [comment]
hi , i edit it, let post more clear.
I said that root permission is required to make the Kasini3000 linux MASTER pc more secure. Do you understand? Because there are fewer broilers with root permission.

As for your reason, do you think it is safer for ssh clients to execute without root permission on linux MASTER pc?
Do you think the ftp client with root permission on linux is insecure?

**Comment by rhubarb-geek-nz** [comment]
FTP is a protocol that nobody uses anymore because it uses no encryption.

Yes, it is better login to a remote system as a non-root user and only use root permissions to do the required tasks than to login as root and do everything as root on the remote system.

This is why on AWS you get access to a new EC2 as user "ec2-user", on Azure you can enter the name you want, and on Oracle Cloud it is as "opc". Then once you log into the machine you can use sudo to perform individual commands that need root access.

**Comment by kasini3000** [comment]
According to my understanding of the topic, this topic has nothing to do with NODE.

The point of view in the theme is: 
**On the MASTER computer!!!** 
It is safer to execute powershell scripts with non root permissions.

My answer is: 
You can never prove that executing the ssh client with root authority is not safe ON MASTER computer.

**Comment by rhubarb-geek-nz** [comment]
Yes it is safer to execute PowerShell scripts with non root permission on the master. If the master node is executing tasks on a node then it has no need to be root on the master machine.

**Comment by kasini3000** [comment]
```
#ssh xxx@ip command
```
Please prove UP command is DANGER to CLIENT LINUX than DOWN.
```
$ssh xxx@ip command
```

**Comment by rhubarb-geek-nz** [comment]
As you yourself said, if the master node is compromised then all nodes are compromised.

Code that is not running as root on the master has less chance of causing corruption on the master due to bug in software or misconfiguration.

**Comment by kasini3000** [comment]
# A:Use root authority to send commands to the node pc through the ssh client. There are no security problems in master linux. Because it is to send commands, rather than execute commands from remote locations.So,Users need a tool that is easy to use, not a pair of handcuffs.

**Comment by rhubarb-geek-nz** [comment]
You said that on Windows the Master node does not need to run as an Administrator, so why does the master node on a Linux system need to run as root?
