### ISSUE TITLE
Suggest use hash-bang /usr/bin/env pwsh to assist Linux users

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#7]
I notice that when following the installation instructions for Linux users, that none of the *.ps1 files have the execution bit set.

It is traditional, in a Linux environment, to simply be able to run scripts from the command line no matter what interpreter they use.

For PowerShell this means adding this as the first line..

`#/usr/bin/env pwsh
`

This would be before the param block.

Then set the execution bit for the program using...

`chmod +x xxxx.ps1
`

To update this in git use

`git add --chmod=+x xxxx.ps1
`

So then for Linux users they don't have to prefix running a PowerShell script with "pwsh".

**Comment by kasini3000** [comment]
### sha-bang:
sha-bang is negative & harmful & redundant

### ps1 execution authority:
Kasini3000 does not intend to comply with the execution authority of ps1,
Pwsh does not comply with the execution authority of ps1.
Each time you add a command, you need to maintain the permission list, which is negative for the project.

Do not think of ps1 as a script file, but as a configuration file of pwsh. Your anxiety will be solved at once.
