### ISSUE TITLE
Suggest kasini3000 uses an environment variable such as KASINI3000_HOME to determine location of files

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#8]
Most software allows the user the option of where to install software and then configure it using environment variables so it can operate

For example..

DOTNET_HOME
JAVA_HOME
CATALINA_HOME/CATALINA_BASE
ANSIBLE_CONFIG
GIT_EXEC_PATH

Suggest that kasini3000 uses an environment variable to determine where its files are to support users who don't want to use the default install location.

**Comment by kasini3000** [comment]
It only provides customized directory services for big paying customers.
