### ISSUE TITLE
Suggest login to node should not use root account

### ISSUE THREAD

**Issue by rhubarb-geek-nz** [kasini3000/kasini3000#9]
In the LICENSE.TXT it says

```
kasini3000 will overwrite your old ssh pub key file on linux node. ---> /root/.ssh/authorized_keys .The old pub key will invalid.

The node machine account password is stored in plain text on the master machine.

```

It is not considered good practice to remote login as root. As an example, when you create a new virtual machine in AWS or Oracle Cloud you get SSH with a non-root user who can then use sudo to execute administration commands.

I suggest that a similar approach is done with kasini3000 where it uses a non-root user to login and run scripts, then only use sudo for specific administration commands.

I would also suggest that once you have a public key in ~/.ssh/authorized_keys then kasini3000 no longer needs the password to the node. All access would be secure and authenticated by SSH.

**Comment by kasini3000** [comment]
> In the LICENSE.TXT it says

warning:  override key-file.Ok, I adjusted my English slightly to make it clearer

---

> kasini3000 no longer needs the password to the node

win，linux master to linux node step：
1 only use keyfile start pssession,never use username-pwd . 
rsa-4096 keyfile1 ,if fail, user keyfile2.
2 if fail,try use username-pwd login,and push local key file to remote.


---

### A: Sudo is not necessary for root (system management). It is necessary to use root+keyfile for remote management, and there is no need to change it.

You should know that the world's first RHEL linux does not actively use sudo for OS managers, For root and management tasks, sudo is redundant.

btw: 

Powershell & powershell team currently does not support pssession + sudo on linux remote(from win,linux, master to linux node).

**Comment by kasini3000** [comment]
Tip: 
These scripts can be provided to work through password, non-root + sudo. 
C:\ ProgramData\ kasini3000\ k_copyfrom_ip_port_w2l_user_expect_pwd.ps1. 
C:\ ProgramData\ kasini3000\ k_copyto_ip_port_w2l_user_expect_pwd.ps1. 
C:\ ProgramData\ kasini3000\ k_run_ip_port_w2l_user_expect_pwd.ps1
